### ISSUE TITLE
Considering major changes to Slackord

### ISSUE THREAD

**Issue by richfromm** [thomasloupe/Slackord1#8]
Apologies if this is not the best place to discuss this, I don't think GitHub has a way (or at least not any more) for me to privately message you @thomasloupe 

As I somewhat mentioned in some discussion in https://github.com/thomasloupe/Slackord/pull/7, I don't see a lot of value in the tkinter GUI, esp. given the way it hangs currently, and I'm considering making this just a simple command line script:
* https://github.com/thomasloupe/Slackord/pull/7#issuecomment-1229546059
* https://github.com/thomasloupe/Slackord/pull/7#issuecomment-1229547249
* https://github.com/thomasloupe/Slackord/pull/7#issuecomment-1229549645

But now I'm thinking of going way further than that. (And I've written some test code for some of this.) Some other changes I'd like to make:
* Do away with the bot nature altogether. Rather than type `!slackord` in the destination channel and have the bot (sort of) pull the messsges, instead have the script (sort of) push the messages to a given channel based on id.
* At first I thought the above would be a bit of a pain (b/c you need to enable developer mode and do something in the GUI to get the channel id), but I figured out how to do this programmatically.
* Support pointing to not just a single channel at a time, but a directory structure of per channel json files, which is what the slack export gives you.
* Possibly support mapping slack channel names to discord channel names if they're not the same.
* Pass token either on the command line, or via an env var, or persist via a file (either in the cwd, or user's home dir)

I'm totally fine making these changes within the context of this project, and creating PR's for you to merge from my fork at https://github.com/richfromm/Slackord . But if I do all of the above, it ultimately won't bear that much resemblance to the bot that you originally wrote. And I can also totally understand if this isn't something you want to spend a lot of time or energy on, since this was just something you coded a while back in your spare time, and esp. since you also have https://github.com/thomasloupe/Slackord2 . So I'd also be fine doing a hard fork (and maybe renaming it something similar but somewhat different, like slackordcli), and just continuing development on my own. I would of course credit you as the original author.

Let me know if you have a preference.

**Comment by thomasloupe** [comment]
I honestly don't see how to make many of those points user-friendly from a command-line perspective but you might have a way (possibly a config file or something). That's jumping into quite a big list of arguments that need to be parsed. I personally find it easier to just create the channels I want to import to and import to them. In a situation where I don't want the bot to create a channel for me, in a CLI environment, I need to specify via some argument that I do or don't want that.

Passing the token via some file in the same directory as Slackord would make sense. Since Python is not OS specific your best bet is to just ensure a text file called `Token.txt` or `Token.json` is present in the working directory which is much easier than coding three separate home dirs, one for each respective OS.

Slackord uses a Discord bot instead of API calls because it automatically handles rate-limiting, which doing otherwise turns into a massive issue once you've posted about 20 messages and begin getting rate limited. Additionally, the bot logs when things fail, whether that's due to connection issue, permissions, or otherwise.

I recognize that the Tkinter version of the app is pretty busted with threading the bot itself, and I'm all for making it a CLI-only script, but it bears the risk of making it even less user-friendly by requiring lots of arguments to be passed. Then there's also [Slackord2](https://github.com/thomasloupe/Slackord2) as you said, which does all the things Slackord1 doesn't do except thread support.

I would honestly hand you the keys to Slackord1 if I didn't use most of the code and the rest of the repos I have here as resume talking points. For that reason alone, I'd prefer if there weren't too many commits from other folks, otherwise I'd be happy to just merge any and all changes you did. I can't show future potential employers someone else's code and tell them "I created this" from an honest standpoint (I'm sure you understand where I'm coming from), so the best course of action would be to create a hard fork. I could link your fork in the main repo as well.

**Comment by richfromm** [comment]
I totally understand where you're coming from.

I've done some initial work on a proof of concept, and I'm probably going to move forward with it, and I'm totally fine with creating a hard fork. Feel free to keep this open until I either decide to do that or not to do it, if you want a link to it in your README. (Or of course you can feel free to close this now if you don't want to be bothered with keeping it open.)

In the course of experimenting, however, I discovered a minor bug in my threading addition (a missing warning). And when fixing that, I slightly improved the case that is being warned about. Covered in https://github.com/thomasloupe/Slackord/pull/9

**Comment by richfromm** [comment]
@thomasloupe do you care at all about future work I do on this in a fork?

Specifically, do you want me adding you as a reviewer on my changes (e.g. https://github.com/richfromm/Slackord/pull/1) ?
I'm not actually 100% sure how to do that, I suspect I'd need to add you as a collaborator on the project. I'm okay with either a yes or a no, totally up to you.

I'm also happy to take feedback as to whether or not you have a preference for me keeping the name in the fork, or changing the name of the repo, as discussed [here](https://github.com/richfromm/Slackord/pull/1#issue-1368376747). I don't have enough experience with forks in GitHub to know whether or not a name change has any other side effects, like whether GH still recognizes and displays it as a fork. I assume it probably doesn't matter, but I suppose the convention is that forks only change the org, and not the repo name, so a change might be confusing to people. Or maybe a change is better if the normal convention is the same name with a different org is just for external contributions that are ultimately intended to merge upstream.

**Comment by richfromm** [comment]
Seems like renaming a fork is no big deal: https://github.blog/changelog/2022-04-12-you-can-now-name-your-fork-when-creating-it/

**Comment by thomasloupe** [comment]
I don't mind at all.
I think it is better to have it renamed just for clarity sake, but maybe you could do something like `slackord-newnamehere`. I don't need any attribution at all personally, but if it derived from the original slackord, it might be a nicety. However, I'm specifically stating now, that neither do I require nor expect such from your own forks.

As far as contributions/reviews are concerned, it's your fork! No need to run changes by me, the derivative name in the fork is good enough should you decide to go that route. Also fine if not!

I have enough with Slackord2 that I'm happy someone wants to pick up Slackord1 and give it QoL and a future.

**Comment by richfromm** [comment]
I've made a bunch of changes in my [fork](https://github.com/richfromm/slack2discord) and released it as [2.0](https://github.com/richfromm/slack2discord/releases/tag/2.0)

This includes all of the features and changes originally proposed here. I am therefore closing this issue.

I have a few more changes I am considering in the near term (see [Future work](https://github.com/richfromm/slack2discord#future-work)), if so, these will also be on the fork.
